name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev python3-dev
        
    - name: Install project
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[dev]
    
    - name: Run tests
      run: |
        mkdir -p data/raw data/processed
        pytest tests/ -v --cov=src --cov-report=xml